name: uri_converter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/martinsellergren/uri_converter

environment:
  sdk: ^3.5.4

dependencies:
  collection: ^1.0.0
  cartesian_product: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
