name: uri_converter
description: Convert between uri and your data model.
version: 1.2.0
repository: https://github.com/martinsellergren/uri_converter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.0.0
  cartesian_product: ^1.0.0
  freezed_annotation: ^2.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^4.0.0
  test: ^1.24.0
